export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const ADD_TOTABLE = 'ADD_TOTABLE'
export const ADD_NEWDATA = 'ADD_TONEWDATA'
export const CLEAR_NEWDATA = 'CLEAR_TONEWDATA'
export const CHANGE_REGDATE = 'CHANGE_REGDATE'
export const CHANGE_USERID = 'CHANGE_USERID'
export const CHANGE_LASTACTIVEDATA = "CHANGE_LASTACTIVEDATA"
